name = "julia_cf2"
uuid = "87e84bbb-d1ca-462b-86a1-8813b166f916"
authors = ["Sarath S Menon <sarathmenon.downey@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
